baseURL = "https://sumone.love/"
title = "Sumit Kumar"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "https://blog.sumone.love/"
    weight = 10

  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 20


  [[menu.main]]
    name = "Social-Pages"
    url = "/social-pages"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 50

  [[menu.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/sumo1e"
    weight = 10

  [[menu.social]]
    name = "YouTube"
    pre = "youtube"
    url = "https://youtube.com/@sumonelove"
    weight = 20

  [[menu.social]]
    name = "RSS Feed"
    pre = "rss"
    url = "/index.xml"
    weight = 30



[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
